version: "3.9"
services:
  sonardb:
    container_name: sonardb
    image: postgres:latest
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DATABASE: sonar
    volumes:
      - postgresql_sonar:/var/lib/postgresql
      - postgresql_sonar_data:/var/lib/postgresql/data
  invenusdb:
    container_name: invenusdb
    image: postgres:latest
    environment:
      POSTGRES_USER: invenus
      POSTGRES_PASSWORD: invenus
      POSTGRES_DATABASE: invenus
    volumes:
      - postgresql_invenus:/var/lib/postgresql
      - postgresql_invenus_data:/var/lib/postgresql/data
  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    command: server /data1 --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin # todo: change
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data1:/data1
  web:
    container_name: invenus-web
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - sonarqube
      - invenus-server
      - minio
    ports:
     - "80:8000"
  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  invenus-server:
    container_name: invenus-server
    build:
      context: .
      dockerfile: docker/invenus-server/Dockerfile
    depends_on:
      - invenusdb
      - minio
    environment:
      LOG_PATH: /app/logs
    volumes:
      - invenus_logs:/app/logs
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_sonar:
  postgresql_sonar_data:
  postgresql_invenus:
  postgresql_invenus_data:
  invenus_logs:
  data1:
