version: "3.3"
services:
  invenusdb:
    container_name: invenusdb
    image: postgres:latest
    environment:
      POSTGRES_USER: invenus
      POSTGRES_PASSWORD: invenus
      POSTGRES_DATABASE: invenus
    volumes:
      - postgresql_invenus:/var/lib/postgresql
      - postgresql_invenus_data:/var/lib/postgresql/data
  web:
    container_name: invenus-web
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - invenus-server
    ports:
     - "80:8000"
  invenus-server:
    container_name: invenus-server
    build:
      context: .
      dockerfile: docker/invenus-server/Dockerfile
    depends_on:
      - invenusdb
    environment:
      LOG_PATH: /app/logs
    volumes:
      - invenus_logs:/app/logs
volumes:
  postgresql_invenus:
  postgresql_invenus_data:
  invenus_logs:
