version: "3.9"
services:
  sonardb:
    image: postgres:latest
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DATABASE: sonar
    volumes:
      - postgresql_sonar:/var/lib/postgresql
      - postgresql_sonar_data:/var/lib/postgresql/data
  invenusdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: invenus
      POSTGRES_PASSWORD: invenus
      POSTGRES_DATABASE: invenus
    volumes:
      - postgresql_invenus:/var/lib/postgresql
      - postgresql_invenus_data:/var/lib/postgresql/data
  web:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - sonarqube
      - invenus-server
    ports:
     - "80:8000"
  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  invenus-server:
    build:
      context: .
      dockerfile: docker/invenus-server/Dockerfile
    depends_on:
      - invenusdb
    environment:
      LOG_PATH: /app/logs
    volumes:
      - invenus_logs:/app/logs
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_sonar:
  postgresql_sonar_data:
  postgresql_invenus:
  postgresql_invenus_data:
  invenus_logs:
